name: Deploy website

on:
  push:
    branches:
      - master-source

jobs:
  deploy:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/master-source'
    steps:
      - name: Run deploy script
        run: npm run deploy
